/*
 Generated by typeshare 1.7.0
*/

export interface User {
	id: string;
	name: string;
}

export interface NewUser {
	name: string;
}

export interface Person {
	name: string;
	age: number;
	favorite_food?: string;
}

